# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvBRjW0orZEvJMAFefegO1qNap8rjZQ_

```markdown
# Uno Game Implementation

이 노트북은 4인용 우노 게임을 구현합니다. 1명의 플레이어와 3명의 봇이 게임에 참여합니다.

## 1. 게임 구성 요소 정의 (카드, 덱, 플레이어)
```
"""

!pip install streamlit
import streamlit as st
import time # 봇 턴 진행 시 지연을 위해 사용

import random

class Card:
    def __init__(self, color, value):
        self.color = color
        self.value = value

    def __str__(self):
        return f"{self.color} {self.value}"

    def __repr__(self):
        return f"Card('{self.color}', '{self.value}')"

    def is_action_card(self):
        return self.value in ['Skip', 'Reverse', 'Draw Two', 'Wild', 'Wild Draw Four']

class Deck:
    def __init__(self):
        self.cards = []
        colors = ['Red', 'Yellow', 'Green', 'Blue']
        values = [str(i) for i in range(10)] + ['Skip', 'Reverse', 'Draw Two']

        # Add colored cards
        for color in colors:
            for value in values:
                self.cards.append(Card(color, value)) # One of each for 0-9, Skip, Reverse, Draw Two
                if value != '0':
                    self.cards.append(Card(color, value)) # Two of each for 1-9, Skip, Reverse, Draw Two

        # Add Wild cards (4 of each)
        for _ in range(4):
            self.cards.append(Card('Wild', 'Wild'))
            self.cards.append(Card('Wild', 'Wild Draw Four'))

        self.shuffle()

    def shuffle(self):
        random.shuffle(self.cards)

    def draw_card(self):
        if not self.cards:
            print("Deck is empty, reshuffling discard pile into new deck.")
            # In a real game, you'd reshuffle the discard pile here.
            # For simplicity, we'll just create a new full deck if empty.
            self.__init__() # Re-initialize deck for demo purposes
            self.shuffle()
        return self.cards.pop()

    def __len__(self):
        return len(self.cards)

class Player:
    def __init__(self, name, is_bot=True):
        self.name = name
        self.hand = []
        self.is_bot = is_bot

    def add_card(self, card):
        self.hand.append(card)

    def remove_card(self, card_to_remove):
        for i, card in enumerate(self.hand):
            if card.color == card_to_remove.color and card.value == card_to_remove.value:
                return self.hand.pop(i)
        return None # Card not found

    def get_playable_cards(self, top_card, current_color_override=None):
        playable_cards = []
        for card in self.hand:
            # If Wild card was played, current_color_override dictates the playable color
            if current_color_override and card.color == current_color_override:
                playable_cards.append(card)
            elif card.color == 'Wild': # Wild cards can always be played
                playable_cards.append(card)
            elif card.color == top_card.color or card.value == top_card.value:
                playable_cards.append(card)

        return playable_cards

    def __str__(self):
        return f"{self.name} (봇: {self.is_bot})"

    def __repr__(self):
        return self.name


# --- Test basic classes ---
deck = Deck()
print(f"Initial deck size: {len(deck)}")

player1 = Player("플레이어 1", is_bot=False)
bot1 = Player("봇 1", is_bot=True)

for _ in range(7):
    player1.add_card(deck.draw_card())
    bot1.add_card(deck.draw_card())

print(f"\n{player1.name}의 손패: {player1.hand}")
print(f"{bot1.name}의 손패: {bot1.hand}")
print(f"Deck size after dealing: {len(deck)}")

"""```markdown
## 2. 게임 로직 구현

이제 우노 게임의 핵심 로직을 구현합니다. 여기에는 턴 관리, 카드 플레이 규칙, 특수 카드 처리, 승리 조건 등이 포함됩니다.
```
"""

class UnoGame:
    def __init__(self, num_bots=3):
        self.deck = Deck()
        self.players = []
        self.players.append(Player("플레이어", is_bot=False))
        for i in range(num_bots):
            self.players.append(Player(f"봇 {i+1}", is_bot=True))
        random.shuffle(self.players) # Randomize player order

        self.discard_pile = []
        self.current_player_idx = 0
        self.direction = 1 # 1 for clockwise, -1 for counter-clockwise
        self.current_color_override = None # Used for Wild cards
        self.game_over = False
        self.winner = None
        self.turn_advanced_by_action = False # New flag to prevent double turn advancement

    def deal_initial_cards(self, num_cards=7):
        for player in self.players:
            for _ in range(num_cards):
                player.add_card(self.deck.draw_card())

    def start_game(self):
        self.deal_initial_cards()

        # Place the first card on the discard pile (must not be a Wild Draw Four)
        while True:
            first_card = self.deck.draw_card()
            if first_card.value != 'Wild Draw Four':
                self.discard_pile.append(first_card)
                self.current_color_override = first_card.color if first_card.color != 'Wild' else None
                break
            else: # Reshuffle if it's a Wild Draw Four
                self.deck.cards.insert(0, first_card) # Put it back to deck
                self.deck.shuffle()

        print("--- 우노 게임 시작 ---")
        print(f"첫 번째 카드: {self.get_top_card()}")
        if self.current_color_override:
            print(f"현재 유효 색상: {self.current_color_override}")

        # Handle first card actions (Skip, Reverse, Draw Two, Wild)
        # Note: Initial card actions also need to set turn_advanced_by_action if they advance turn
        self.handle_initial_card_action(first_card)

        while not self.game_over:
            self.play_turn()

    def get_top_card(self):
        return self.discard_pile[-1]

    def get_current_player(self):
        return self.players[self.current_player_idx]

    def advance_turn(self, skip_next=False):
        if skip_next:
            # Skip the next player by advancing the index an extra time
            self.current_player_idx = (self.current_player_idx + self.direction) % len(self.players)

        self.current_player_idx = (self.current_player_idx + self.direction) % len(self.players)

        # Ensure index is positive if it wraps around negatively (due to self.direction = -1)
        if self.current_player_idx < 0:
            self.current_player_idx += len(self.players)

    def handle_initial_card_action(self, card):
        # For simplicity, we'll only handle non-Wild Draw Four as initial card
        if card.value == 'Skip':
            print(f"첫 번째 카드 'Skip'! {self.get_current_player().name} 턴이 건너뛰어집니다.")
            self.advance_turn(skip_next=True)
            self.turn_advanced_by_action = True
        elif card.value == 'Reverse':
            print(f"첫 번째 카드 'Reverse'! 게임 방향이 바뀝니다.")
            self.direction *= -1
        elif card.value == 'Draw Two':
            print(f"첫 번째 카드 'Draw Two'! {self.get_current_player().name}가 카드 2장을 뽑습니다.")
            current_player = self.get_current_player()
            current_player.add_card(self.deck.draw_card())
            current_player.add_card(self.deck.draw_card())
            self.advance_turn()
            self.turn_advanced_by_action = True
        elif card.color == 'Wild': # Wild or Wild Draw Four, but Wild Draw Four is handled
            print(f"첫 번째 카드 'Wild'! 색상 {card.color}로 시작합니다.")
            # For initial Wild, we assume it's played without explicit color choice
            # or default to its color, which is 'Wild'. We already set current_color_override.
            # No special turn advancement needed.
            pass


    def player_turn_logic(self, player):
        print(f"\n--- {player.name}의 턴 ---")
        top_card = self.get_top_card()
        print(f"현재 덱 맨 위 카드: {top_card}")
        if self.current_color_override:
            print(f"현재 유효 색상: {self.current_color_override}")

        playable_cards = player.get_playable_cards(top_card, self.current_color_override)

        print(f"{player.name}의 손패: {player.hand}")

        if not playable_cards:
            print(f"{player.name}는 낼 카드가 없어 카드 한 장을 뽑습니다.")
            drawn_card = self.deck.draw_card()
            player.add_card(drawn_card)
            print(f"뽑은 카드: {drawn_card}")
            print(f"{player.name}는 낼 카드가 없어 턴을 마칩니다.")
            return

        print("낼 수 있는 카드:")
        for i, card in enumerate(playable_cards):
            print(f"{i}: {card}")

        while True:
            try:
                choice_idx = int(input("낼 카드의 번호를 입력하세요 (카드를 뽑으려면 -1 입력): "))
                if choice_idx == -1:
                    print(f"{player.name}는 카드를 뽑습니다.")
                    drawn_card = self.deck.draw_card()
                    player.add_card(drawn_card)
                    print(f"뽑은 카드: {drawn_card}")
                    print(f"{player.name}는 낼 카드가 없어 턴을 마칩니다.")
                    break

                chosen_card = playable_cards[choice_idx]
                self.play_card(player, chosen_card)
                break
            except (ValueError, IndexError):
                print("유효하지 않은 입력입니다. 다시 시도해주세요.")

    def bot_turn_logic(self, player):
        print(f"\n--- {player.name}의 턴 (봇) ---")
        top_card = self.get_top_card()
        print(f"현재 덱 맨 위 카드: {top_card}")
        if self.current_color_override:
            print(f"현재 유효 색상: {self.current_color_override}")
        # print(f"{player.name}의 손패: {player.hand}") # Removed this line

        playable_cards = player.get_playable_cards(top_card, self.current_color_override)

        if playable_cards:
            # Bot strategy: Try to play a matching color/number card first, then action cards, then wild.
            # A simple strategy for now: just pick the first playable card.
            card_to_play = None

            # Prioritize matching color/number
            for card in playable_cards:
                if card.color == self.current_color_override or card.value == top_card.value:
                    card_to_play = card
                    break

            # If no direct match, check action cards (excluding Wild Draw Four for now)
            if not card_to_play:
                for card in playable_cards:
                    if card.is_action_card() and card.value != 'Wild Draw Four':
                        card_to_play = card
                        break

            # If still no card, play a Wild card or Wild Draw Four
            if not card_to_play:
                 for card in playable_cards:
                    if card.color == 'Wild':
                        card_to_play = card
                        break

            if card_to_play:
                self.play_card(player, card_to_play)
                return

        # If no playable cards, draw a card
        print(f"{player.name}는 낼 카드가 없어 카드 한 장을 뽑습니다.")
        drawn_card = self.deck.draw_card()
        player.add_card(drawn_card)
        print(f"{player.name}가 뽑은 카드: {drawn_card}")
        print(f"{player.name}는 낼 카드가 없어 턴을 마칩니다.")


    def play_card(self, player, card):
        player.remove_card(card)
        self.discard_pile.append(card)
        print(f"{player.name}가 {card} 카드를 냈습니다.")
        self.current_color_override = card.color if card.color != 'Wild' else None

        # Handle action cards
        if card.value == 'Skip':
            print(f"'Skip' 카드! 다음 플레이어의 턴이 건너뛰어집니다.")
            self.advance_turn(skip_next=True)
            self.turn_advanced_by_action = True
        elif card.value == 'Reverse':
            print(f"'Reverse' 카드! 게임 방향이 바뀝니다.")
            self.direction *= -1
            if len(self.players) == 2: # In a 2-player game, Reverse acts like Skip
                 self.advance_turn(skip_next=True)
                 self.turn_advanced_by_action = True
        elif card.value == 'Draw Two':
            print(f"'Draw Two' 카드! 다음 플레이어가 카드 2장을 뽑고 턴을 건너뜁니다.")
            self.advance_turn() # Advance to the next player to draw
            next_player = self.get_current_player()
            next_player.add_card(self.deck.draw_card())
            next_player.add_card(self.deck.draw_card())
            print(f"{next_player.name}가 카드 2장을 뽑았습니다.")
            self.advance_turn() # Skip their turn
            self.turn_advanced_by_action = True
        elif card.value == 'Wild':
            print(f"'Wild' 카드! 색상을 선택합니다.")
            if player.is_bot:
                # Bot chooses the color it has most of, or a random color
                colors_in_hand = [c.color for c in player.hand if c.color != 'Wild']
                if colors_in_hand:
                    chosen_color = max(set(colors_in_hand), key=colors_in_hand.count)
                else:
                    chosen_color = random.choice(['Red', 'Yellow', 'Green', 'Blue'])
                print(f"{player.name}가 {chosen_color} 색상을 선택했습니다.")
                self.current_color_override = chosen_color
            else:
                while True:
                    color_choice = input("원하는 색상을 선택하세요 (Red, Yellow, Green, Blue): ").capitalize()
                    if color_choice in ['Red', 'Yellow', 'Green', 'Blue']:
                        self.current_color_override = color_choice
                        break
                    else:
                        print("유효하지 않은 색상입니다. 다시 시도해주세요.")
        elif card.value == 'Wild Draw Four':
            print(f"'Wild Draw Four' 카드! 다음 플레이어가 카드 4장을 뽑고 턴을 건너뜁니다.")
            if player.is_bot:
                colors_in_hand = [c.color for c in player.hand if c.color != 'Wild']
                if colors_in_hand:
                    chosen_color = max(set(colors_in_hand), key=colors_in_hand.count)
                else:
                    chosen_color = random.choice(['Red', 'Yellow', 'Green', 'Blue'])
                print(f"{player.name}가 {chosen_color} 색상을 선택했습니다.")
                self.current_color_override = chosen_color
            else:
                while True:
                    color_choice = input("원하는 색상을 선택하세요 (Red, Yellow, Green, Blue): ").capitalize()
                    if color_choice in ['Red', 'Yellow', 'Green', 'Blue']:
                        self.current_color_override = color_choice
                        break
                    else:
                        print("유효하지 않은 색상입니다. 다시 시도해주세요.")

            self.advance_turn() # Advance to the next player to draw
            next_player = self.get_current_player()
            for _ in range(4):
                next_player.add_card(self.deck.draw_card())
            print(f"{next_player.name}가 카드 4장을 뽑았습니다.")
            self.advance_turn() # Skip their turn
            self.turn_advanced_by_action = True

        self.check_for_uno(player)
        self.check_winner(player)

    def check_for_uno(self, player):
        if len(player.hand) == 1:
            print(f"!!! {player.name} 우노! !!!")

    def check_winner(self, player):
        if not player.hand:
            self.game_over = True
            self.winner = player
            print(f"!!! {player.name} 승리! 게임 종료! !!!")

    def play_turn(self):
        current_player = self.get_current_player()
        self.turn_advanced_by_action = False # Reset flag for each turn

        if current_player.is_bot:
            self.bot_turn_logic(current_player)
        else:
            self.player_turn_logic(current_player)

        if not self.game_over and not self.turn_advanced_by_action:
            self.advance_turn()
            print(f"다음 턴: {self.get_current_player().name}")

# --- Game Setup and Start (Commented out to prevent accidental run) ---
# game = UnoGame(num_bots=3)
# game.start_game()

"""```markdown
## 3. 게임 실행

위 코드를 실행하여 게임을 시작할 수 있습니다. `UnoGame` 클래스의 인스턴스를 생성하고 `start_game()` 메서드를 호출하세요.
```
"""

# 게임 인스턴스 생성 및 시작
# 이 셀을 실행하면 우노 게임이 시작됩니다.

uno_game = UnoGame(num_bots=3)
uno_game.start_game()